---
title: "EIP"
output:
  pdf_document: default
  html_notebook: default
editor_options:
  markdown:
    wrap: 72
---

## Model formulation:

Writing down the formulation to model the mosquito population. The
equation describing the susceptible mosquito is as follows :

$$ \frac{dS(t)}{dt} = b - \beta S(t)  I_H(t) - \mu_S S(t), $$

where is the $b$ is the birth rate and should be equal to the sum of the
mortality terms and senescent development terms to ensure a constant
population; $\beta$ is the infection rate where we assume a law of mass
action between the susceptible vectors and the infected vertebrate host,
$I_H$; and finally, the background mortality term, $\mu_S$.

The infected mosquitoes then flow into the exposed class $E$ which we
describe as the stage where the vectors are not yet infectious to
vertebrate hosts:

$$\frac{dE(t)}{dt} = \beta S(t) I_H(t) - \int_{t-\tau}^{t} E(t-\tau)e^{-\mu_I \tau} f(\tau) d\tau - \mu_E E(t),$$

The integrodifferential equation describes the mosquitos that enter the
exposed class $\tau$ days ago, survive (expressed by the exponential
decay), and multiplied by the probability distribution function $f(t)$
of the waiting time. Due to the difficulty of simulating this, we
converted the integrodifferential equation into a series of ordinary
differential equation by using the 'linear chain trick'. By assuming
that the pdf is a gamma-distribution, the above equation can be written
as:

$$ \frac{dE_1(t)}{dt} = \beta S(t) I_H(t) - n \alpha_E E_1(t) - \mu_EE_1(t) \quad k = 1 $$

$$\frac{dE_k}{dt} = n \alpha_E E_{k-1}(t) - n \alpha_E E_{k}(t)  - \mu_E E_k(t) \quad k >1$$

Here, $n$ is the number of subcompartments within the model and
describes the variability in which individuals transition. Specifically,
the coefficient of variation (CV) is $\frac{1}{\sqrt(n)}$. Exposed
individuals than transition into the infectious compartment:

$$
\frac{dI}{dt} = n \alpha_E E_{n}(t) - \alpha_II(t) 
$$

## The full model formulation with double feeding

We need to modify the full model formulation to create two different
compartments. We declare $D(t)$ for exposed mosquitos that have doubled
fed and $DI$(t) for the double infected. We must first modify the
exposed class and a new outflow fo the exposed class is $f(V_H)E_0$
which describe the rate at which the exposed class double feed:

$$
\frac{dE_1(t)}{dt} = \beta S(t) I_H(t) - f(V_H)E_0(t) -  n \alpha_E E_0(t) - \mu_E E_0(t) \quad k = 1 \\ $$

$$\frac{dE_k(t)}{dt} = n \alpha_E E_{k-1}(t) - n \alpha_E E_{k}(t) - f(V_H)E_k(t) - \mu_E E_k(t) \quad k > 1\\$$

The double-fed states that are still not infectious are then described
below:

$$
\frac{dD_1}{dt} = f(V_H)E_1(t) -  n_D \alpha_D D_1(t)- \mu_D D_1(t) \quad k =1\\
$$ $$
\frac{dD_k}{dt} = f(V_H)D_k(t) +  n_D \alpha_D D_{k-1}(t) - n_D \alpha_D D_{n}(t)  - \mu_E D_k(t) \quad k  >1 \\
$$

Then we have the double-fed individuals go into the $DI$ compartment:

$$
\frac{dDI(t)}{dt}=  n_D \alpha_D D_{n_D}(t) - \alpha_{DI}DI(t) 
$$

Important assumptions in the model we must think about for the second
model:

1)  Susceptible mosquitos do not double feed (should we change this). I
    can imagine it changes the model because with double feeding, maybe
    you can greatly increase the change of being infected by the
    vertebrate host AND increase your lifespan.

2)  When you're an infected mosquito, we assume that the mortality is
    exponentially distributed.

3)  Assume a law of mass action when it comes to susceptible host and
    vertebrate hosts

Things we have to talk about:

1.  Vertebrate host - we want to keep the vertebrate host (\$V_H\$) in
    the model at equilibrium?

2.  Biting rate and the infection rate have to be linked (i just
    haphazardly put different numbers in here, but the infection rate
    must include the daily biting rate)

## Calculating R0 using the next generation matrix

Haven't calculated R0 as complicated as this- is there a way to
partition which group is contributing more to the R0 (partioning it in a
way?). First pass because of the multiple compartments mean that we
might have to the next generation matrix method. First question, what is
the difference in R0 with and without double feeding.
